name: Deploy CDK Infrastructure
on:
  push:
    branches:
      - master

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    permissions:
      # Permissions needed for OIDC
      id-token: write
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::588738601991:role/GithubActionsRole
          aws-region: us-east-2

      - name: Deploy CDK Infrastructure
        working-directory: infrastructure
        run: |
          npm install
          npm run build
          npm run cdk:deploy -- --require-approval never --all